ipfs/awesome-ipfs

README.md
davidar/markup.rocks#1
> Don't mention IPFS in the description as it's implied.
Since this is a port of an existing non-IPFS app, I think it makes sense to explicitly mention IPFS. The other option would be to create a separate category for ported apps?
> The pull request should have [...] why it should be included.
Because it rocks ;)
=> Add markup.rocks

README.md
Some people were confused by this. Cf. https://github.com/ipfs/community/issues/69. This text should help!
=> Added clarification about already built stuff

README.md
http://beets.radbox.org/ is a great command line music library manager and metadata tagger.
There's documentation on the plugin here https://beets.readthedocs.org/en/v1.3.15/plugins/ipfs.html
=> Added beets-ipfs

README.md
Hi! I've been working on a distributed social platform and data sharing web app for a few months now, and I'm nearing a first usable release. Technically it works already and there's a version that runs without go-ipfs installed, in any modern browser. But I don't consider it reliable yet.
I thought about adding it here so that I can get some more feedback about it. And also because I hope it's at least a little bit cool :+1: 
Check it out: [website](http://boards.ydns.eu) [repo](https://github.com/fazo96/ipfs-boards)
=> added ipfs-boards

README.md
This way I don't have to curate DNS entries for servers and if someone is using browser plug-in the transformation works.
=> Update link to hasteIPFS to link global gateway

README.md
Sorry for changing it again but that form is final.
I couldn't know that I would buy ipfs.ovh when I was PRing it last time.
=> Change URL of hasteIPFS to new domain

README.md
for starters, i'm not @hydrusnetwork, i'm just adding this for him.
The Hydrus Network is "a personal booru-style media tagger that can import files and tags from your hard drive and popular websites. Content can be shared with other users via user-run servers."
=> Add HydrusNetwork

README.md
When I added this mirror, somehow a twitter shortlink was added instead of the one to the public gateway. So I corrected it
=> Correct twitter shorted link

README.md
(1) update Eris URL
(2) removed dead URL with .pics gTLD; left link to GitHub repo
(3) IPRedirect: The originally linked ipfs-userscript had problems: the first version was redirecting to https-localhost instead of http-localhost, i.e. not working, and the current version is kinda working, but it doesn't support complex ipfs/ipns paths; not sure what happened there, because I thought I had gotten it to work. So I'm offering a new redirect script from my own repo that should (hopefully!) work; it also checks for a local ipfs node and only redirects, if it's actually running. The script should also move to "Tools", where the browser addons/extensions are.
=> README.md: error fixes & new item

README.md
🎉 Adds Siderus Orion 🎉
Our goal is to develop an easy to use and to set up to have a full IPFS node running in background. It is designed around users that are not familiar with IPFS, so that it won't require the use command line but Orion allows the access to the network. Current state: uses Electron and `go-ipfs` with drag-and-drop-like features (aka make it easy-peasy), as well as _pre-caching_ on various gateways, displays not just hashes but also the file names if available and explore IPFS objects with more details (as a File/Property explorer). More feature will come soon :)
Feedback and help is more than welcome 👍
=> 🎉 Adds Siderus Orion 🎉

README.md
We just launched new version of our Demo DApp which makes (IMHO) pretty incredible use of IPFS. 
It's used for listing images, listing data, user profile pictures, user attestations (ERC 725), and more. 
Blog post with more detail on what's new: https://medium.com/originprotocol/tech-update-dapp-gets-erc-725-identity-transaction-steps-escrow-reviews-298a7c91b7a5
Original blog post (January): https://medium.com/originprotocol/origin-demo-dapp-is-now-live-on-testnet-835ae201c58
=> Added Origin Protocol Demo Dapp

README.md
Pathephone uses IPFS to share music as well as discover and stream music shared by others.
=> add app: Pathephone

src/js/app.js
So I just improved the search a little bit. Now, if you type, let's say, `mark`, it will show everything that starts with "mark" and not only the results that match exactly "mark". 
I didn't do the same for backwards search (like searching for `down` and finding results ending in `down`) because it makes the search slower. Source:
> Leading wildcards, as in the above example, should be used sparingly. They can have a negative impact on the performance of a search, especially in large indexes.
> https://lunrjs.com/guides/searching.html#wildcards
License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>
=> feat: improved search

README.md, data/apps.yaml
I removed filemap from the app.yaml and README.md files, as it doesn't use ipfs anymore.
I can't run `npm run build:readme`, so I just updated the README manually. If this doesn't suffice, feel free to make this change yourself ;)
=> Remove filemap.xyz

README.md, data/tools.yaml
`ipfs-gui` and `ipfs-linux-service` had double entries.
=> Delete doubled entries

README.md, data/apps.yaml
It has changed for some reason:
* https://ipfsstore.it/about.php
* https://steemit.com/@ipfsstore/transfers
=> change IPFSStore  description bitcoin -> steem

.circleci/config.yml, .travis.yml
This:
1. Moves all the workflows to Circle CI.
2. Allows failures on `ipfs.io` for timing outs.
License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>
=> chore: remove travis and just use circle

pull_request_template.md
Created a pr template in an effort to resolve #187 
This should ensure changes to the /data folder are made instead of changes to the README.md directly.
The PR template is below.
-------
Does this pull request include an item addition/removal/edit? yes/no
If you answered yes to the previous question, ensure that your answers to the following questions are all yes; otherwise, delete this template and draft your own PR.
Did you edit the `/data` directory instead of the [README.md](https://github.com/ipfs/awesome-ipfs/blob/master/README.md)? yes/no
Does this PR include only one addition/removal/edit? yes/no
Did you run the `make build` command following your edits to the `/data` directory? yes/no
Have you followed the [CONTRIBUTING.md …
=> docs: create PR template

src/css/app.css, src/js/app.js, src/layouts/_default/baseof.html, src/layouts/partials/list.html
First of all, this removes the grow effect when hovering around items (fixes #241). The effect wasn't really helping with anything in the interface by causing blurriness. Perhaps in the feature we can find a better way to give focus to the current 'hovered' item.
Secondly, this makes the page wider and stops using flex boxes for the columns and uses CSS columns instead. With this, the items don't need to be vertically aligned, so they don't need to take up the same space. That way, this won't happen anymore:
Of course this has its own drawbacks: the bottom items aren't aligned and perfectly beautiful. But I believe this is a much better looking solution than having big empty blocks.
The max columns we have is four, and they adapt to 3, 2 and 1 at certain breaking points.
License: MIT …
=> feat: wider page and better columns

README.md, data/datasets.yml
It was added https://github.com/ipfs/archives/pull/199/files but somehow to lost in the migration from a static page to a dynamically generated page.
=> Readd WistfulBooks/LibriVox to datasets

README.md, data/apps.yaml
Removed https://t.bdaily.club as it returns 502 (using github repo URL instead).
cc https://github.com/ipfs/awesome-ipfs/pull/228 
@facert feel free re-add website URL in separate PR if you plan to fix it.
=> fix: remove broken link for DtinyUrl

README.md, scripts/readme-template.md
The collab clusters are listed on a dedicated webpage, so I only added a static text to the readme which contains a link to the webpage. 
Listing them in two locations doesn't make much sense, I guess.
=> add collab clusters as a fixed entry to the readme

README.md, data/apps.yaml
A working example of an application using IPFS for service discovery as described here: https://github.com/ipfs/notes/issues/15
Once other peers are discovered, IPNS is used to locate a manifest of signed posts to be considered for replication. 
I mostly consider this project a technology preview of sorts, it was very educational for myself and hope it could teach others. Built using django & vue, configured to run using docker-compose.
=> Add pugdit to application list

.github/workflows/data.yml
=> feat: auto build without run build locally

src/layouts/partials/list.html
This PR is to fix formatting/layout issues in how text and images fit on cards on awesome.ipfs.io.
Line breaking in paragraphs in cards was set to "break-all" and would
break lines in the middle of words, making reading difficult. Changing
to "break-word" tries to break between words or at hyphens, which makes
reading cards much easier.
In addition, the headers and paragraphs in cards had a maximum width set
using the mw5 class tag, which is set as 16rem in ./src/static/app.css.
However, this maximum width only spans around 3/4 of width of the
card, so there was a column of whitespace on the right hand side of …
=> Fix mid-word line breaks & right-side whitespace

README.md, data/apps.yaml
There are lots of excellent chat applications using WebRTC and JS-IPFS, all requiring signaling servers, some not very easy to install. So, going along a different track, decided to build a very basic chat app that 
1. uses only standard GNU/Linux command-line tools and the Go-IPFS CLI
2. doesn't need any special server like the WebRTC apps
3. works over both LAN and internet (including NAT traversal)
4. provides secure chatrooms, private messaging and in-chat file & directory sharing
`ipfs-chat` achieves all these and is run from a single Bash script !
- [Github …
=> Added app: ipfs-chat

.github/workflows/broken_link_cron.yml, scripts/remove-broken-links.js
Fix issues where job would run and still attempt to commit and create PR if
no errors were reported.
See https://github.com/ipfs/awesome-ipfs/actions/runs/3064434657/jobs/4947529925
Also see manual runs on the branch this PR is for: https://github.com/ipfs/awesome-ipfs/actions/workflows/broken_link_cron.yml
=> fix: broken-links workflow
