ipfs/awesome-ipfs

README.md

Added some more apps/tools/videos/articles.

Add things

---

README.md

Maybe we want to order them by date published?

Added two articles

---

README.md

Added http2ipfs (and testing GitCop)

---

README.md

Not sure if we should have newest articles in the top or in the bottom. Please let me know and I'll move it to the bottom instead.

Add article about downloading nodejs versions over ipfs

---

README.md

Added ipget and ipcat

---

README.md

Added Discussions

---

README.md

Added apps from ipfs/community#12

---

README.md

Added webapps

---

README.md

My small, fully static, IPFS based, code viewer. // For now, upload will be there.

Add HasteIPFS

---

LICENSE
README.md

Part of standard-readme standardization. https://github.com/ipfs/community/issues/124

Added badges, contribute, and License file

---

README.md

Added the Changelog episode

---

README.md

Added the "The Internet Democratised" article
Added domain to the changelog episode
Removed the "Press" header
closes #54

Add "The Internet Democratised" article, del "press" header

---

README.md

See https://github.com/ipfs/awesome-ipfs/pull/56#discussion_r79292964

Update ToC, rename to `Articles and Press`

---

.travis.yml

instead of just going through changed files, I'm proposing here to check all the links in README.md, on every change. To verify that everything still works when we modify master.

Run awesome_bot on all the links!

---

README.md

Global Upload is a file transportation service for IPFS, upload files to the future of distributed web.

Add globalupload.io

---

README.md

Added the ipfs-search search engine, as suggested in https://github.com/ipfs/archives/issues/8#issuecomment-259163500

Added ipfs-search to apps.

---

README.md

beaker browser: add

---

README.md

Added platforms

---

README.md

Link to site was dead. Changed to only github

Deleting dead link

---

README.md

Proposing to add this tool I wrote as [suggested by VictorBjelkholm](https://github.com/ipfs/js-ipfs-api/pull/512#issuecomment-275930042)

Add ipfs-add-from-url

---

README.md

https://github.com/beakerbrowser/beaker/issues/455

Remove BeakerBrowser due 2 dropped support of IPFS

---

README.md

Hey folks, here's an app I built to make it super simple for dev's and non-dev's alike to add files to IPFS.
**Download:** [partysha.re](https://partysha.re)
**Github:** [BusterLabs/Partyshare](https://github.com/BusterLabs/Partyshare)

Add partyshare to apps

---

README.md

Hi everyone.
I'm building a friend-to-friend file-sharing app on top of IPFS. It would be nice to be added here :)

Add Arbore

---

README.md

Added gogo.tattoo. We think it's a right place for us.
http://gogo.tattoo/aid
http://gogo.tattoo/xizi
http://gogo.tattoo/gogo
http://gogo.tattoo/klimin

Added gogo.tattoo.

---

README.md

Add IPFS-GUI

---

README.md

SnapCloud is made by @alexsicart.
https://github.com/alexsicart/Decentralized-Cloud

feat(readme): Add SnapCloud

---

README.md

[Temporal](https://github.com/RTradeLtd/Temporal)  is an easy to use API and platform for integrating IPFS and other distributed/decentralized storage technologies into enterprise applications

Add Temporal Project

---

README.md

[Textile Photos](https://www.textile.photos) is a secure, open source, digital wallet for your photos. It runs a fully working IPFS peer on mobile devices (iOS and Android), supports sharing, encryption, and p2p communications. [GitHub](https://github.com/textileio/textile-mobile)

Add Textile Photos

---

README.md

Added: * [ipfs-add-from-encrypted](https://github.com/TroyWilson1/ipfs-add-from-encrypted) - Encrypt a file with AES256 then add to IPFS

Add ipfs-add-from-encrypted

---

README.md

As suggested by @fsdiogo in https://github.com/ipfs/notes/issues/289#issuecomment-404843919
License: MIT
Signed-off-by: Pascal Precht <pascal.precht@gmail.com>

Add article on future-proof cryptographic hashes

---

ci/Jenkinsfile

Enable publishing of website on change

---

README.md
data/tools.yaml

This will update the details about Siderus Orion

Updates Siderus Orion details

---

src/layouts/_default/baseof.html

fix: add right url to suggest an item

---

README.md
scripts/readme-template.md

As a new contributor I want to know how to build the readme and website before publishing the PR.
Closes #159

Adds a simple text to explain how to build before PR.

---

README.md
data/articles.yaml

I presented this poster last year at RECOMB 2017, not sure if `articles` is the best category but the other ones seems even less appropriate 😆

add RECOMB 2017 poster on "Decentralized indexes for public genomic data"

---

README.md
data/tools.yaml

See https://github.com/moxystudio/gatsby-plugin-ipfs

Add gatsby-plugin-ipfs to tools section

---

README.md
scripts/readme-template.md

Fix Broken Link for Contributing

---

data/apps.yaml

Update apps.yaml to reflect updated copy describing Qri

---

README.md
data/tools.yaml

Web app to check public states of IPFS gateways, including latency and gateway writable state. Link to application [here](https://ipfs.fooock.com/)

Tool to check public gateways states

---

README.md
data/datasets.yml

Updates the XKCD archive to a version I'm maintaining through DNSlink. It's updated automatically every day to make sure it's up to date 😃 
Also, closes #193
License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

feat: update xkcd archive

---

README.md
data/apps.yaml
data/articles.yaml
data/datasets.yml
data/tools.yaml

This removes the failing links.
License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

fix: remove non-existing

---

README.md
data/tools.yaml

Sweet IPFS is an Android app that aims to fully run and manage an IPFS node from your phone.
It is forked from IPFSDroid, which was experimental. This app is currently in beta stage, not all features are implemented, but the most important is. Feel free to test it and review it. If you find a bug or have problems with this app, you can contact me with the email provided on the Google Play page.
Sweet IPFS targets end-users and developers in order to make IPFS (and decentralization) an everyday standard. Its main goal is to be used as a file sharing app. For that, it provides a file chooser, QR codes, and a browser. To go even faster, you can upload a file or a text directly from any app by simply sharing it and choosing Sweet IPFS.
At the current point, battery and network usage depends a …

Added "Sweet IPFS" Android app

---

src/layouts/_default/baseof.html
src/layouts/partials/analytics.html

📈
ref: https://github.com/protocol/metrics/issues/1

chore: add google analytics

---

README.md
data/articles.yaml

License: MIT
Signed-off-by: Vaibhav Saini <vasa@towardsblockchain.com>
Added an article on Multiformats

chore: add multiformats tutorial

---

README.md
data/apps.yaml

feat: update TODO demo link

---

README.md
data/apps.yaml

<https://github.com/bdchain/Minerva>
Minerva is a storage plugin of Apache Drill that connects IPFS's decentralized storage and Drill's flexible query engine. Any data file stored on IPFS can be easily accessed from Drill's query interface, just like a file stored on a local disk.

Add Minerva

---

README.md
data/articles.yaml

License: MIT
Signed-off-by: Vaibhav Saini <vasa@towardsblockchain.com>

feat: add understanding ipfs series

---

README.md
data/tools.yaml

Rename - git-stellar-ipfs -> go-stellar-ipfs

Rename - git-stellar-ipfs to go-stellar-ipfs

---

data/services.yaml

Add Peergos as a service. This is the hosted version of Peergos.

Add Peergos as a service

---

README.md
data/apps.yaml

feat: add Diffuse

---

README.md
data/articles.yaml

feat: add 'The Case for Decentralized Social Network' article

---

README.md
data/apps.yaml

ipfscloud seems to not exist anymore.

fix: remove ipfscloud

---

README.md
data/apps.yaml

Create a simple note-taking web app which stores notes on IPFS. The app is meant to be a friendly, non-technical demonstration of an app which uses IPFS.

feat: add ipjot to apps list

---

README.md
data/apps.yaml

feat: add IPSE to apps list

---

CONTRIBUTING.md
POLICY.md

Meta: Add content policy from #150 and note it in the contribution guide.

feat: content policy (#150)

---

README.md
data/apps.yaml
data/services.yaml
data/tools.yaml

This PR replaces broken links and removes entry if no working one could be found.
Hopefully will fix the awesome_bot check at CI.

fix: ensure all links work

---

.circleci/config.yml
.gitignore
CONTRIBUTING.md
Makefile
README.md
package-lock.json
scripts/readme-template.md

This PR adds `package-lock.json` to speed up install and the CI build.

feat: faster build via npm ci

---

README.md
data/articles.yaml

License: MIT
Signed-off-by: Vaibhav Saini <vasa@towardsblockchain.com>

feat: add libp2p chat article

---

README.md
data/articles.yaml
package-lock.json

License: MIT
Signed-off-by: Vaibhav Saini <vasa.develop@gmail.com>
Added a new article to the articles list.

Add IPLD golang article

---

README.md
data/articles.yaml

License: MIT
Signed-off-by: Vaibhav Saini <vasa@signy.io>
Added Building a twitter bot article ;)

Add twitter bot article

---

data/datasets.yml

Fix Geocities dataset size

---

README.md
data/apps.yaml

Change cyber description. Update dao site to app site
Edited cyber description + changed link leading to dao website, to the actual app site

Update cyber info: change dao link to app link

---

README.md
data/apps.yaml
data/datasets.yml

fix: typos

---

README.md
data/tools.yaml

I created a bash-script command which encrypt the files using a passphrase or a keypair before uploading it using IPFS. I documented it both in English and Japanese, I was told to add it here in the awesome repo! I also wrote about it [here](https://dev.to/terceranexus6/tellit-3joc).

Adding a new tool

---

README.md
data/tools.yaml

feat: add go-orbit-db to tools

---

README.md
data/apps.yaml

Added Tree3 Network in apps, source code URL is also provided for reference.

Added tree3 network in data/apps.yaml

---

README.md
data/apps.yaml

Fix broken link to http://www.alexandria.io

---

README.md
data/apps.yaml

Remove a broken link to bin.ipfs.ovh

---

README.md
data/datasets.yml

This archive was created by myself over the course of about a year. It was recommended to me in the Reddit thread that I submit this dataset to awesome-ipfs. Due to the content split between a remote server that is hosting the files and my home computer with which I modified the repository, I was not able to `git push` commits after I ran `make build`. Instead, I was forced to do it via the Github panel. I hope this is not an issue.
Right now, it is about 50GB in size, and has reached a few thousand people on Reddit and IA.
Since, to my knowledge, this is the biggest archive of cooking recipes in the world, I …

Add Cooking Recipes dataset

---

README.md

Rather than towards meta-repositories.

README: point users towards discuss.ipfs.io

---

README.md
scripts/readme-template.md

Readme: point to discourse

---

README.md
data/datasets.yml

It might be intresting that this appears to be the largest data set yet, in this repository.
Syzygy tablebases are used to analyse games in the chess community. The tablebase server hosted by lichess.org is hit with 5-10 probes per second, depending on the time of day. Most of these are triggered by a user interaction (like making a move on an analysis board), but the number of users is not tracked.
Due to the difficulty of downloading very large tablebase files from traditional mirrors, the majority of users do not have offline access to Syzygy tables. IPFS enables dowloading only the relevant blocks for offline …

Add 7-piece Syzygy tablebases

---

README.md

The current IETF RFC archive linked to in the README is dead in the waters and is 3 years old, and  like 50% of the files listed dont even resolve anymore.
I've created a list that's up-to-date as of yesterday [here](https://gateway.temporal.cloud/ipns/rfcs.temporal.cloud) and it's hosted by Temporal's production IPFS cluster so resolution speeds shouldn't be a problem. If desired I can create a separate PR to link to this DNSLink record which I'll be updating whenever I have free time to download new RFCs, hopefully once a month.
Not sure how to answer this. Really it's just a personal tool to add RFCs to IPFS. …

Add IETF RFC Archiving And Indexing Tool 

---

README.md
data/tools.yaml

Revert "Add IETF RFC Archiving And Indexing Tool "

---

README.md
data/apps.yaml

- [ x] This PR includes only one addition, removal, or edit.
- [ x] I edited the `/data` directory instead of the [README.md](https://github.com/ipfs/awesome-ipfs/blob/master/README.md).
- [ x] I ran the `make build` command following my edits to the `/data` directory.
- [ x] I reviewed the [content policy](https://github.com/ipfs/awesome-ipfs/blob/master/POLICY.md) and the and the [IPFS Community Code of Conduct](https://github.com/ipfs/community/blob/master/code-of-conduct.md) to ensure my submission meets the requirements.
- [ x] I have followed the [CONTRIBUTING.md …

computes is acquired few years ago

---

CONTRIBUTING.md
pull_request_template.md

Thanks to https://github.com/ipfs/awesome-ipfs/pull/340 we no longer need contributors to run a script to update the readme, it happens automatically on merge 🎉

Contributors no longer need to rebuild the readme before submitting PRs

---

README.md
data/tools.yaml

no
undetermined
undetermined
no

Add galacteek in data/tools.yaml

---

data/tools.yaml

chore: add gomobile-ipfs

---

data/tools.yaml

[IPFS Setup Action](https://github.com/marketplace/actions/ipfs-setup-action) facilitates easy cross-platform testing environment in GitHub's CI platform for tools/libraries/applications that rely on IPFS.
This was primarily created cross-platform matrix testing of IPWB.
This is applicable to any tools, libraries, and applications that needs to be tested against IPFS daemon.

Add IPFS Setup Action

---

.circleci/config.yml
README.md
data/articles.yaml
data/services.yaml

Fixing and removing some 404ing links that are breaking CI

Fixed a couple 404ing links

---

data/apps.yaml

- [ * ] **Adding** something new to awesome-ipfs
- [ * ] This PR includes only one addition, removal, or edit.
- [ * ] I edited the `/data` directory instead of the [README.md](https://github.com/ipfs/awesome-ipfs/blob/master/README.md).
- [ * ] I reviewed the [content policy](https://github.com/ipfs/awesome-ipfs/blob/master/POLICY.md) and the and the [IPFS Community Code of Conduct](https://github.com/ipfs/community/blob/master/code-of-conduct.md) to ensure my submission meets the requirements.
- [ * ] I have followed the [CONTRIBUTING.md guidelines](https://github.com/ipfs/awesome-ipfs/blob/master/CONTRIBUTING.m …

Add Skyhook to the apps list

---

data/apps.yaml

Add Everforo

---

data/apps.yaml

Could use more contributors 
~1000 people from communities I'm in (it's new)
~20 billion people on Earth, Moon and Mars
Would be cool if data would propagate faster, we could add a lot more features \o/

added messenger

---

README.md
data/datasets.yml

- [x ] **Adding** something new to awesome-ipfs
- [x ] This PR includes only one addition, removal, or edit.
- [x ] I edited the `/data` directory instead of the [README.md](https://github.com/ipfs/awesome-ipfs/blob/master/README.md).
- [x ] I have followed the [CONTRIBUTING.md guidelines](https://github.com/ipfs/awesome-ipfs/blob/master/CONTRIBUTING.md).
- [x ] Essential
- [x ] Permanent archiving

Adding OSMA to data/datasets.yml

---

README.md
data/tools.yaml

N/A
N/A
N/A
I am looking forward to using the pinning service API to build a code collaboration platform.

Add Multiverse to tools.

---

data/apps.yaml

Extremely small. More of a POC than anything else.
I do not know how to answer this question.

Added Ipgit

---

README.md
data/tools.yaml

Add ipfs-pinner and wbipfs

---

data/apps.yaml

Fix image typo

---

data/tools.yaml

https://github.com/justicenode/node-ipns-pin
Why it should be included? Because it can be a useful tool for when you want to help others pin their site but are too lazy to update the pins manually if the cid changes.

added ipns-pin

---

data/tools.yaml

https://github.com/ethanwu155/awesome-ipfs
Why it should be included? Because no-code movement represents accessibility. It allows for people without programming backgrounds to develop. IPFS from URL Bubble Plugin will help to connect no-code movement with web3.0 and ipfs. 
Bubble IPFS plugin currently got official listing on the Bubble Plugin page and currently has 15 installs.
Bubble is a No-Code platform that currently serves over 250k customers. We believe that No-Code movement is strong and providing tools via plugins to support (such as IPFS integration) to support Web3.0 development will be extremely …

add bubble ipfs from url plugin

---

data/apps.yaml

Update apps.yaml (fix IPFS-FPS website)

---

data/apps.yaml

Add DreamLink to apps.yaml

---

data/apps.yaml

Edited Terrive in data/apps.yml to fix a typo

Edited Terrive in data/apps.yml

---

data/services.yaml

Unstoppable marketplace in the IPFS network.

Add IPFSBay

---

README.md
data/apps.yaml
data/articles.yaml
data/datasets.yml
data/services.yaml

cleans up things reported by:
https://app.circleci.com/pipelines/github/ipfs/awesome-ipfs/1064/workflows/14f3c043-fc5f-496c-85bd-c05a1759e4ed/jobs/1743

chore: remove dead links

---

.circleci/config.yml
README.md
scripts/readme-template.md
src/config.yaml

chore: move to awesome.ipfs.tech (and to Fleek)

---

data/apps.yaml
data/tools.yaml

See https://app.circleci.com/pipelines/github/ipfs/awesome-ipfs/1155/workflows/3a0e7492-db09-4859-8219-d4ac50df169e/jobs/1858
- [N/A] **Adding** something new to awesome-ipfs
- [N/A] **Editing** something already listed on awesome-ipfs
- [N/A] **Something else** *(if so, please explain in the "Additional details" section below)*
See failing circleci job: https://app.circleci.com/pipelines/github/ipfs/awesome-ipfs/1155/workflows/3a0e7492-db09-4859-8219-d4ac50df169e/jobs/1858?invite=true&invite=true#step-103-298
Issues :-(
> Links 
1. [L049]  https://cyber.page Failed to open TCP connection to cyber.page:443 …

fix: Remove entries with broken links

---

dangerfile.js

feat: Fail PRs that edit README.md

---

data/apps.yaml

update ipfs-fps cid

---

scripts/readme-template.md

Updates the readme template with a call for maintainers.
partially resolves https://github.com/ipfs/ipfs-gui/issues/100#issuecomment-1319233546

chore: Add call for maintainers to README

---

README.md

Adding link to https://durin.site

Add Durin to README.md

---

README.md

Since IPFS is a protocol and one of our priorities is to get support across multiple platforms (especially the web), it makes sense to highlight where we have browser support IMO

Create browsers section

---

README.md

Add bifrost gateway to tools

---

README.md

Move valist from Apps to Platforms

---

README.md

https://github.com/meandavejustice/pin-tweet-to-ipfs

Add Pin Tweet to IPFS to README.md

---

README.md
stale.md

create stale.md for unmaintained projects

---

README.md

add link to implementations section of ipfs.tech

---

README.md

Add Opera browser

---

README.md

https://github.com/quasarch/dump-ipfs
This project uniquely integrates IPFS/Filecoin with popular DBMS solutions, offering a decentralized backup agent suitable for diverse environments. 
Using Web3 Storage, it taps into IPFS's decentralized nature, providing secure, encrypted backups, ensuring data integrity and security. 
With PostgreSQL support and plans for Delta-optimized enterprise backups, the tool exemplifies how IPFS can modernize and decentralize traditional SaaS solutions, showcasing IPFS's versatility in real-world applications. Such innovation makes it a valuable addition to this collection of awesome ipfs tools.

Add dump-ipfs tool

---

README.md

IPFS + Tor for e2ee chat, desktop and mobile clients available

Adding Quiet chat app

---

README.md
stale.md

Removed ipgit from README and moved to stale

---

README.md

add note about stale projects

---

README.md

added [Matters.town](https://matters.town/)

adding Matters.town

---

README.md

adding gw3.app

---

README.md

chore: updated Pinning Service

---

README.md

Update the pinning services list

---

README.md

Add IPFS-boot to README under section Tools
